### ISSUE TITLE
Doesn't seem to work for me

### ISSUE THREAD

**Issue by assembledadam** [ypereirareis/docker-satis#39]
Docker compose file as follows:

```
satis:
    image: ypereirareis/docker-satis:4.2
    ports:
        - 8888:3000
        - 5000:80
```

@ port 5000, satis looks good.
@ port 8888 I get `Cannot GET /`

Same for requesting /admin - Cannot GET /admin
